# Set the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY app/backend/src/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY app/backend/src .

# Expose the port that the application listens on
EXPOSE 3000

# Command to run the application
CMD ["node", "./index.js"]