# Set the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY app/frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY app/frontend/ .

# Expose the port on which the application listens
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]
