version: "3.9"

services:
  frontend:
    build:
      context: ../../
      dockerfile: docker/dockerfiles/Dockerfile.frontend
    ports:
      - "5000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ../../
      dockerfile: docker/dockerfiles/Dockerfile.backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    build:
      context: ../../
      dockerfile: docker/dockerfiles/Dockerfile.database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: